
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    289.0,
    148.0,
    991.0,
    598.0,
    fill="#151515",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=855.0,
    y=537.0,
    width=86.0,
    height=24.0
)

canvas.create_text(
    348.0,
    493.0,
    anchor="nw",
    text="20 Hz",
    fill="#FF2D00",
    font=("Roboto", 12 * -1)
)

canvas.create_text(
    481.0,
    493.0,
    anchor="nw",
    text="500Hz",
    fill="#EAFF00",
    font=("Roboto", 12 * -1)
)

canvas.create_text(
    413.0,
    493.0,
    anchor="nw",
    text="100Hz",
    fill="#FF7A00",
    font=("Roboto", 12 * -1)
)

canvas.create_text(
    550.0,
    493.0,
    anchor="nw",
    text="800Hz",
    fill="#8EFF00",
    font=("Roboto", 12 * -1)
)

canvas.create_text(
    881.0,
    493.0,
    anchor="nw",
    text="20.000Hz",
    fill="#0084FF",
    font=("Roboto", 12 * -1)
)

canvas.create_text(
    619.0,
    493.0,
    anchor="nw",
    text="1000Hz",
    fill="#05FF00",
    font=("Roboto", 12 * -1)
)

canvas.create_text(
    750.0,
    493.0,
    anchor="nw",
    text="5000Hz",
    fill="#00FFD1",
    font=("Roboto", 12 * -1)
)

canvas.create_text(
    685.0,
    493.0,
    anchor="nw",
    text="2000Hz",
    fill="#00FF84",
    font=("Roboto", 12 * -1)
)

canvas.create_text(
    812.0,
    493.0,
    anchor="nw",
    text="10000Hz",
    fill="#00D1FF",
    font=("Roboto", 12 * -1)
)

canvas.create_text(
    884.0,
    251.0,
    anchor="nw",
    text="Bass Boost",
    fill="#FFFFFF",
    font=("Roboto", 12 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=882.0,
    y=178.0,
    width=64.0,
    height=64.0
)

canvas.create_text(
    805.0,
    251.0,
    anchor="nw",
    text="Vocals",
    fill="#FFFFFF",
    font=("Roboto", 12 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=791.0,
    y=178.0,
    width=64.0,
    height=64.0
)

canvas.create_text(
    717.0,
    251.0,
    anchor="nw",
    text="Piano",
    fill="#FFFFFF",
    font=("Roboto", 12 * -1)
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=700.0,
    y=178.0,
    width=64.0,
    height=64.0
)

canvas.create_text(
    599.0,
    251.0,
    anchor="nw",
    text="Acoustic Guitar",
    fill="#FFFFFF",
    font=("Roboto", 12 * -1)
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=609.0,
    y=178.0,
    width=64.0,
    height=64.0
)

canvas.create_text(
    529.0,
    251.0,
    anchor="nw",
    text="E-Guitar",
    fill="#FFFFFF",
    font=("Roboto", 12 * -1)
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=518.0,
    y=178.0,
    width=64.0,
    height=64.0
)

canvas.create_text(
    439.0,
    251.0,
    anchor="nw",
    text="Vintage",
    fill="#FFFFFF",
    font=("Roboto", 12 * -1)
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=427.0,
    y=178.0,
    width=64.0,
    height=64.0
)

canvas.create_text(
    346.0,
    251.0,
    anchor="nw",
    text="Custom",
    fill="#FFFFFF",
    font=("Roboto", 12 * -1)
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=335.0,
    y=178.0,
    width=64.0,
    height=64.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    641.0,
    386.0,
    image=image_image_1
)

canvas.create_rectangle(
    296.55999755859375,
    122.0,
    991.0,
    148.0,
    fill="#292929",
    outline="")

canvas.create_text(
    331.99993896484375,
    129.0,
    anchor="nw",
    text="Track 0 Equalizer",
    fill="#5B5B5B",
    font=("Roboto", 12 * -1)
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=302.99993896484375,
    y=131.0,
    width=10.0,
    height=10.0
)

canvas.create_rectangle(
    288.99993896484375,
    122.0,
    295.99993896484375,
    148.0,
    fill="#02ECFE",
    outline="")
window.resizable(False, False)
window.mainloop()
